# Generated by Django 5.0.3 on 2024-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
