version: "3.9"
name: expertmeet

services:
  frontend-web-server:
    container_name: expertmeet-frontend-web-server
    build:
      src/frontend/web
    ports:
      - 80:80
    depends_on:
      - expertmeet-nginx-server
      - notifications-nginx-server
      - conversations-nginx-server

  expertmeet-nginx-server:
    env_file:
      - .env
    container_name: expertmeet-nginx-server
    build:
      src/backend/expertmeet/nginx
    ports:
      - 8080:8080
    depends_on:
      - expertmeet-django-server

  expertmeet-django-server:
    env_file:
      - .env
    container_name: expertmeet-django-server
    expose:
      - 8000
    build:
      src/backend/expertmeet
    depends_on:
      - expertmeet-db-postgres

  expertmeet-db-postgres:
    container_name: expertmeet-web-db
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-nginx-server:
      container_name: notifications-nginx-server
      env_file:
      - .env
      build:
        src/backend/notifications
      ports:
        - 8081:8081
      depends_on:
        - notifications-django-server

  notifications-django-server:
      container_name: notifications-django-server
      env_file:
      - .env
      expose:
        - 8000
      build:
        src/backend/notifications
      depends_on:
        - notifications-db-postgres

  notifications-celery-server:
    container_name: notifications-celery-server
    env_file:
      - .env
    build:
      context: src/backend/notifications
      dockerfile: DockerfileCelery
    depends_on:
      - notifications-django-server
      - celery-message-broker

  notifications-db-postgres:
    container_name: notifications-db-postgres
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-notifications:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  conversations-nginx-server:
        container_name: conversations-nginx-server
        env_file:
        - .env
        ports:
          - 8082:8082
        build:
          src/backend/conversations
        depends_on:
          - conversations-django-server

  conversations-django-server:
        container_name: conversations-django-server
        env_file:
        - .env
        expose:
          - 8080
        build:
          src/backend/conversations
        depends_on:
          - db-postgres-conversations

  db-postgres-conversations:
    container_name: expertmeet-conversations-db
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-conversations:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-message-broker:
    container_name: celery-message-broker
    image: rabbitmq
    expose:
      - 5672

volumes:
  db-data:
    driver: local
  db-notifications:
    driver: local
  db-conversations:
    driver: local