name: expertmeet

services:
  frontend-web-server:
    container_name: expertmeet-frontend-web-server
    build:
      src/frontend/web
    ports:
      - 3000:3000 # TODO: change port for prod
      - 80:80
    depends_on:
      - expertmeet-nginx-server
      - notifications-nginx-server
      - conversations-nginx-server
    develop:
      watch:
        - action: rebuild
          path: ./src/frontend/web
          target: /app
          ignore:
          - node_modules/
          - peerJS.Dockerfile
        - action: rebuild
          path: package.json

  frontend-peer-server:
    container_name: expertmeet-frontend-peer-server
    build:
      context: src/frontend/web
      dockerfile: peerJS.Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - frontend-web-server

  expertmeet-nginx-server:
    container_name: expertmeet-nginx-server
    build:
      context: ./src/backend/expertmeet/
      dockerfile: DockerfileNginx
    ports:
      - 8080:8080
    depends_on:
      - expertmeet-django-server

  expertmeet-django-server:
    env_file:
      - .env
    container_name: expertmeet-django-server
    expose:
      - 8000
    build:
      src/backend/expertmeet
    depends_on:
      - expertmeet-db-postgres
    develop:
      watch:
        - action: sync+restart
          path: src/backend/expertmeet
          target: /usr/src/app

  expertmeet-db-postgres:
    container_name: expertmeet-web-db
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    ports:
      - 5430:5432 # TODO: remove after debug is not needed anymore
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-nginx-server:
      container_name: notifications-nginx-server
      build:
        context: ./src/backend/notifications/
        dockerfile: DockerfileNginx
      ports:
        - 8081:8081
      depends_on:
        - notifications-django-server

  notifications-django-server:
      container_name: notifications-django-server
      env_file:
      - .env
      expose:
        - 8000
      build:
        src/backend/notifications
      depends_on:
        - notifications-db-postgres
      develop:
        watch:
          - action: sync+restart
            path: src/backend/notifications
            target: /usr/src/app

  notifications-celery-server:
    container_name: notifications-celery-server
    env_file:
      - .env
    build:
      context: src/backend/notifications
      dockerfile: DockerfileCelery
    depends_on:
      - notifications-django-server
      - rabbit-message-broker

  notifications-db-postgres:
    container_name: notifications-db-postgres
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-notifications:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    ports:
      - 5431:5432 # TODO: remove after debug is not needed anymore
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  conversations-nginx-server:
        container_name: conversations-nginx-server
        ports:
          - 8082:8082
        build:
          context: ./src/backend/conversations/
          dockerfile: DockerfileNginx
        depends_on:
          - conversations-django-server

  conversations-django-server:
        container_name: conversations-django-server
        env_file:
        - .env
        expose:
          - 8000
        build:
          src/backend/conversations
        depends_on:
          - conversations-db-postgres
          - rabbit-message-broker
        develop:
          watch:
            - action: sync+restart
              path: src/backend/conversations
              target: /usr/src/app

  conversations-celery-server:
    container_name: conversations-celery-server
    env_file:
      - .env
    build:
      context: src/backend/conversations
      dockerfile: DockerfileCelery
    depends_on:
      - conversations-django-server
      - rabbit-message-broker

  conversations-db-postgres:
    container_name: conversations-db-postgres
    image: postgres
    user: postgres
    restart: "on-failure"
    volumes:
      - db-conversations:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432 # TODO: remove after debug is not needed anymore
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit-message-broker:
    container_name: rabbit-message-broker
    image: rabbitmq
    expose:
      - 5672

volumes:
  db-data:
    driver: local
  db-notifications:
    driver: local
  db-conversations:
    driver: local