# Generated by Django 5.0.3 on 2024-03-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Public profile'), (1, 'Private profile'), (2, 'Profile under review'), (3, 'Disabled profile')], default=3),
        ),
    ]
