# Generated by Django 5.0.3 on 2024-03-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile')),
                ('ratings_mean', models.FloatField(default=0.0)),
                ('ratings_count', models.IntegerField(default=0)),
            ],
        ),
    ]
