# Generated by Django 5.0.3 on 2024-03-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.UUIDField(default=12, editable=False),
            preserve_default=False,
        ),
    ]
