# Generated by Django 5.0.3 on 2024-03-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_notification_receiver_notification_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='registration_date',
            new_name='created_at',
        ),
    ]
