# Generated by Django 5.0.3 on 2024-05-21 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sender_id', models.IntegerField(editable=False)),
                ('recipient_id', models.IntegerField(editable=False)),
                ('body', models.TextField(max_length=5000)),
                ('send_timestamp', models.DateTimeField(auto_now_add=True)),
                ('view_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('person1', models.IntegerField()),
                ('person2', models.IntegerField()),
            ],
            options={
                'unique_together': {('person1', 'person2')},
            },
        ),
    ]
