# Generated by Django 5.0.3 on 2024-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_recipient_id_alter_message_sender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.IntegerField()),
                ('person2', models.IntegerField()),
            ],
            options={
                'unique_together': {('person1', 'person2')},
            },
        ),
    ]
